services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: 1000
    image: "web-app/go"
    # deploy:
    #     resources:
    #         limits:
    #             cpus: "1"
    #             memory: 2048M
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      WWWUSER: 1000
      GO_APP: 1
      XDEBUG_MODE: "${APP_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${APP_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - ".:/web-app"
      - "go-cache:/web-app/go"
      - "go-bins:/web-app/bin"
    networks:
      - web_app_net
      
networks:
  web_app_net:
    driver: bridge

volumes:
  app-pgsql:
    driver: local
  go-cache:
    driver: local
  go-bins:
    driver: local
